version: '3'
services:

  mysql:
    image: mysql
    ports:
      - 3306:3306
    restart: unless-stopped
    env_file:
      - ./mysql/.env_db
    volumes:
    - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  myapp:
    image: myapp
    restart: always
    ports:
      - 3000:3000
    env_file:
      - ./app/.env_app
    volumes:
      - ./app/:/home/app/
    depends_on:
      - mysql

  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:rw
    depends_on:
      - myapp
